data(state)
statedata = cbind(data.frame(state.x77), state.abb, state.area, state.center,  state.division, state.name, state.region)
str(statedata)
plot(statedata$x, statedata$y)
tapply(statedata$HS.Grad, statedata$state.region, mean)
tapply(statedata$Murder, statedata$state.region, median)
boxplot(statedata$Murder ~ statedata$state.region)
northeast = subset(statedata, statedata$state.region=="Northeast")
boxplot(northeast$Murder ~ northeast$state.name)
lifeExpReg = lm(Life.Exp ~ Population + Income + Illiteracy + Murder + HS.Grad + Frost + Area, data=statedata)
summary(lifeExpReg)
plot(statedata$Income, statedata$Life.Exp)
lifeExpReg = lm(Life.Exp ~ Income + HS.Grad + Frost + Murder , data=statedata)
summary(lifeExpReg)
lifeExpReg = lm(Life.Exp ~ HS.Grad + Population + Income + Frost, data=statedata)
summary(lifeExpReg)
lifeExpReg = lm(Life.Exp ~ Frost + Murder + HS.Grad + Illiteracy, data=statedata)
summary(lifeExpReg)
lifeExpReg = lm(Life.Exp ~ Population + Murder + Frost + HS.Grad, data=statedata)
summary(lifeExpReg)
lifeExpReg = lm(Life.Exp ~ Population + Income + Illiteracy + Murder + HS.Grad + Frost + Area, data=statedata)
summary(lifeExpReg)
lifeExpReg = lm(Life.Exp ~ Population + Murder + Frost + HS.Grad, data=statedata)
summary(lifeExpReg)
sort(predict(lifeExpReg))
statedata$state.name[which.min(statedata$Life.Exp)]
sort(predict(lifeExpReg))
statedata$state.name[which.max(statedata$Life.Exp)]
sort(lifeExpReg$residuals)