elantraData = read.csv("elantra.csv")
train = subset(elantraData, elantraData$Year <= 2012)
test = subset(elantraData, elantraData$Year > 2012)
nrow(train)
lmElantra = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Queries, data=train)
summary(lmElantra)
lmElantra2 = lm(ElantraSales ~ Month + Unemployment + CPI_all + CPI_energy + Queries, data=train)
summary(lmElantra2)
110.69*(3-1)
110.69*(5-1)
train$Month = as.factor(train$Month)
lmElantra3 = lm(ElantraSales ~ Month + Unemployment + CPI_all + CPI_energy + Queries, data=train)
summary(lmElantra3)
train = subset(elantraData, elantraData$Year <= 2012)
cor(train)
train$Month = as.factor(train$Month)
lmElantraM1 = lm(ElantraSales ~ Month + Unemployment + CPI_all + CPI_energy + Queries, data=train)
summary(lmElantraM1)
lmElantraM2 = lm(ElantraSales ~ Month + Unemployment + CPI_energy + CPI_all, data=train)
summary(lmElantraM2)
test$Month = as.factor(test$Month)
salesPrediction = predict(lmElantraM2, newdata=test)
SSE = sum((salesPrediction - test$ElantraSales)^2)
SSE
baselineSales = mean(train$ElantraSales)
SST = sum((baselineSales - test$ElantraSales)^2)
R2 = 1 - SSE/SST
max(abs(salesPrediction - test$ElantraSales))
which.max(abs(salesPrediction - test$ElantraSales))