airlines = read.csv("AirlinesCluster.csv")
summary(airlines)
install.packages("caret")
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
summary(airlinesNorm)
distances = dist(airlinesNorm, method="euclidean")
hierClust = hclust(distances, method="ward.D")
plot(hierClust)
clusterGroups = cutree(hierClust, k = 5)
table(clusterGroups)
tapply(airlines$Balance, clusterGroups, mean)
set.seed(88)
kmeansClust = kmeans(airlinesNorm, centers=5, iter.max=1000)
table(kmeansClust$cluster)
