gerber = load.csv("gerber.csv")
table(gerber$voting)
civic = subset(gerber, civicduty == 1)
hawthrone = subset(gerber, hawthorne == 1)
self = subset(gerber, self==1)
neighbors = subset(gerber, neighbors==1)
nrow(civic[civic$voting ==1,]) / nrow(civic)
nrow(hawthrone[hawthrone$voting ==1,]) / nrow(hawthrone)
nrow(self[self$voting ==1,]) / nrow(self)
nrow(neighbors[neighbors$voting ==1,]) / nrow(neighbors)
logi_md = glm(voting ~ civicduty + hawthorne + self + neighbors, data = gerber , family = "binomial")
summary(logi_md)
predict = predict(logi_md,type = "response")
table(gerber$voting , predict>=0.3)
(134513 + 51966) / (134513+100875+56730+51966)
table(gerber$voting , predict>=0.5)
(235388) / (235388+108696)
library(ROCR)
ROCRpred = prediction(predict, gerber$voting)
as.numeric(performance(ROCRpred, "auc")@y.values)
library(rpart)
library(rpart.plot)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)
CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp=0.0)
prp(CARTmodel2)
CARTmodel3 = rpart(voting ~ civicduty + hawthorne + self + neighbors + sex, data=gerber, cp=0.0)
prp(CARTmodel3)
rpart.plot(CARTmodel3)
CARTmodel4 = rpart(voting ~ control, data=gerber, cp=0.0)
CARTmodel5 = rpart(voting ~ control + sex, data=gerber, cp=0.0)
prp(CARTmodel4,digits = 6)
prp(CARTmodel5,digits = 6)
0.302795 - 0.290456
0.345818 - 0.334176
logi_md2 = glm(voting ~ control + sex,data = gerber,family = "binomial")
summary(logi_md2)
Possibilities = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(logi_md2, newdata=Possibilities, type="response")
abs(predict(CARTmodel5, newdata=Possibilities) - predict(logi_md2, newdata=Possibilities, type="response"))
LogModel2 = glm(voting ~ sex + control + sex:control, data=gerber, family="binomial")
summary(LogModel2)
predict(LogModel2, newdata=Possibilities, type="response")
abs(predict(CARTmodel5, newdata=Possibilities) - predict(LogModel2, newdata=Possibilities, type="response"))