letters = read.csv("letters_ABPR.csv")
letters$isB = as.factor(letters$letter == "B")
set.seed(1000)
spl = sample.split(letters$isB, SplitRatio = 0.5)
train = subset(letters, spl == TRUE)
test = subset(letters, spl == FALSE)
z = table(test$isB)
kable(z)
z[1]/sum(z)
CARTb = rpart(isB ~ . - letter, data=train, method="class")
predictions = predict(CARTb, newdata=test, type="class")
z = table(test$isB, predictions)
kable(z)
sum(diag(z))/(sum(z))
set.seed(1000)
RFb = randomForest(isB ~ . - letter, data=train) 
predictions = predict(RFb, newdata=test)
z = table(test$isB, predictions)
kable(z)
sum(diag(z))/sum(z)
letters$letter = as.factor( letters$letter ) 
set.seed(2000)
spl = sample.split(letters$letter, SplitRatio = 0.5)
train2 = subset(letters, spl == TRUE)
test2 = subset(letters, spl == FALSE)
z = table(test2$letter)
kable(z)
sum(diag(z))/sum(z)
CARTletter = rpart(letter ~ . - isB, data=train2, method="class")
predictLetter = predict(CARTletter, newdata=test2, type="class")
z = table(test2$letter, predictLetter)
kable(z)
sum(diag(z))/sum(z)
set.seed(1000)
RFletter = randomForest(letter ~ . - isB, data=train2)
predictLetter = predict(RFletter, newdata=test2)
z = table(test2$letter, predictLetter)
kable(z)
sum(diag(z))/sum(z)
