census = read.csv("census.csv")
library(caTools)
set.seed(2000)
spl = sample.split(census$over50k, SplitRatio = 0.6)
train = subset(census, spl==TRUE)
test = subset(census, spl==FALSE)
censusglm = glm( over50k ~ . , family="binomial", data = train)
summary(censusglm)
predictTest = predict(censusglm, newdata = test, type = "response")
z = table(test$over50k, predictTest >= 0.5)
kable(z)
sum(diag(z))/sum(z)
z = table(test$over50k)
kable(z)
z[1]/sum(z)
library(ROCR)
ROCRpred = prediction(predictTest, test$over50k)
as.numeric(performance(ROCRpred, "auc")@y.values)
library(rpart)
library(rpart.plot)
censustree = rpart( over50k ~ . , method="class", data = train)
prp(censustree)
predictTest = predict(censustree, newdata = test, type = "class")
z = table(test$over50k, predictTest)
kable(z)
sum(diag(z))/sum(z)
library(ROCR)
predictTest = predict(censustree, newdata = test)
ROCRpred = prediction(predictTest[,2], test$over50k)
as.numeric(performance(ROCRpred, "auc")@y.values)
PredictROC = predict(censustree, newdata = test)
pred = prediction(PredictROC[,2], test$over50k)
perf = performance(pred, "tpr", "fpr")
plot(perf)
set.seed(1)
trainSmall = train[sample(nrow(train), 2000), ]
set.seed(1)
censusrf = randomForest(over50k ~ . , data = trainSmall)
predictTest = predict(censusrf, newdata=test)
z = table(test$over50k, predictTest)
kable(z)
sum(diag(z))/sum(z)
vu = varUsed(censusrf, count=TRUE)
vusorted = sort(vu, decreasing = FALSE, index.return = TRUE)
dotchart(vusorted$x, names(censusrf$forest$xlevels[vusorted$ix]))
varImpPlot(censusrf)
library(caret)
set.seed(2)
fitControl = trainControl( method = "cv", number = 10 )
cartGrid = expand.grid( .cp = seq(0.002,0.1,0.002)) 
train( over50k ~ . , data = train, method = "rpart", trControl = fitControl, tuneGrid = cartGrid )
CARTcv = rpart(over50k~., data=train, method="class", cp=0.002)
predictTest = predict(CARTcv, newdata=test, type="class")
table(test$over50k, predictTest)
sum(diag(z))/sum(z)
prp(CARTcv)
