parole = read.csv("parole.csv")
nrow(parole)
z = table(parole$violator)
kable(z)
str(parole)
parole$state = as.factor(parole$state)
parole$crime = as.factor(parole$crime)
summary(parole$state)
summary(parole$crime)
set.seed(144)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
mod = glm(violator~., data=train, family="binomial")
summary(mod)
1/(1 + exp(-logodds))
predictions = predict(mod, newdata=test, type="response")
summary(predictions)
z = table(test$violator, as.numeric(predictions >= 0.5))
kable(z)
z[4]/(z[4]+z[2])
z[1]/(z[3]+z[1])
sum(diag(z))/sum(z)
z = table(test$violator)
kable(z)
z[1]/z[2]
library(ROCR)

pred = prediction(predictions, test$violator)

as.numeric(performance(pred, "auc")@y.values)
